name: Run Tests

on:
  push:
    branches:
      - main  # Ejecuta la acción en cada push a la rama `main`
  pull_request:
    branches:
      - main  # Ejecuta la acción en cada pull request hacia `main`

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov selenium mongomock psycopg2-binary

    - name: Set up environment variables
      run: |
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_USER=test_user" >> .env
        echo "POSTGRES_PASSWORD=test_password" >> .env
        echo "POSTGRES_DB=test_db" >> .env
        echo "MONGO_URI=mongodb://localhost:27017/" >> .env
        echo "FLASK_SECRET_KEY=secret_key" >> .env
        echo "BASE_URL=http://localhost:5000" >> .env

    - name: Start Flask server
      run: |
        python app.py &
        sleep 5  # Espera a que el servidor Flask inicie completamente

    - name: Run unit tests
      run: |
        pytest --cov=app test/unit/
    
    - name: Run integration tests
      run: |
        pytest --cov=app test/integration/

    - name: Run End-to-End tests
      run: |
        pytest test/e2e/test_e2e.py

    - name: Upload test coverage report
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage
        path: htmlcov/

    - name: Postgres logs (debugging)
      if: failure()
      run: docker logs $(docker ps --filter name=postgres --format "{{.ID}}")

    - name: Mongo logs (debugging)
      if: failure()
      run: docker logs $(docker ps --filter name=mongo --format "{{.ID}}")